### ISSUE TITLE
Fix Color Scheme

### ISSUE THREAD

**Issue by jamiecartin** [jamiecartin/ToDoList#2]
The color scheme is wonky after updating the TasksView. We need to fix this, as it is currently difficult to read in dark mode.

**Comment by jamiecartin** [comment]
The reason this looks different is because the iPhone version we are using in the simulator view is not compatible with the layout. There are two fixes: 1: turn autolayout off, or 2: work to accommodate all devices. Fix 2 is the desirable solution and is the end goal we will be working towards.

**Comment by cipherins** [comment]
aye, sent over message
